# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 331)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.progressBar_Angle_Beta = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Angle_Beta.setEnabled(False)
        self.progressBar_Angle_Beta.setProperty("value", 50)
        self.progressBar_Angle_Beta.setTextVisible(False)
        self.progressBar_Angle_Beta.setObjectName("progressBar_Angle_Beta")
        self.horizontalLayout_3.addWidget(self.progressBar_Angle_Beta)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_Beta = QtWidgets.QLabel(self.centralwidget)
        self.label_Beta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Beta.setObjectName("label_Beta")
        self.verticalLayout_3.addWidget(self.label_Beta)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.progressBar_Angular_Position = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Angular_Position.setEnabled(True)
        self.progressBar_Angular_Position.setProperty("value", 50)
        self.progressBar_Angular_Position.setTextVisible(False)
        self.progressBar_Angular_Position.setObjectName("progressBar_Angular_Position")
        self.horizontalLayout_5.addWidget(self.progressBar_Angular_Position)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.progressBar_Angular_Speed = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Angular_Speed.setProperty("value", 50)
        self.progressBar_Angular_Speed.setTextVisible(False)
        self.progressBar_Angular_Speed.setObjectName("progressBar_Angular_Speed")
        self.horizontalLayout_6.addWidget(self.progressBar_Angular_Speed)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.label_AngularPosition = QtWidgets.QLabel(self.centralwidget)
        self.label_AngularPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AngularPosition.setObjectName("label_AngularPosition")
        self.gridLayout.addWidget(self.label_AngularPosition, 2, 0, 1, 1)
        self.label_AngularSpeed = QtWidgets.QLabel(self.centralwidget)
        self.label_AngularSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AngularSpeed.setObjectName("label_AngularSpeed")
        self.gridLayout.addWidget(self.label_AngularSpeed, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setScaledContents(True)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setScaledContents(True)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.progressBar_Torque = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Torque.setProperty("value", 50)
        self.progressBar_Torque.setTextVisible(False)
        self.progressBar_Torque.setObjectName("progressBar_Torque")
        self.horizontalLayout_7.addWidget(self.progressBar_Torque)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        self.progressBar_Linear_Speed = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Linear_Speed.setProperty("value", 0)
        self.progressBar_Linear_Speed.setTextVisible(False)
        self.progressBar_Linear_Speed.setObjectName("progressBar_Linear_Speed")
        self.horizontalLayout_8.addWidget(self.progressBar_Linear_Speed)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.label_Torque = QtWidgets.QLabel(self.centralwidget)
        self.label_Torque.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Torque.setObjectName("label_Torque")
        self.gridLayout_2.addWidget(self.label_Torque, 2, 0, 1, 1)
        self.label_LinearSpeed = QtWidgets.QLabel(self.centralwidget)
        self.label_LinearSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LinearSpeed.setObjectName("label_LinearSpeed")
        self.gridLayout_2.addWidget(self.label_LinearSpeed, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_9.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_connection = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_connection.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_connection.setFlat(False)
        self.groupBox_connection.setCheckable(False)
        self.groupBox_connection.setObjectName("groupBox_connection")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_connection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_address = QtWidgets.QLineEdit(self.groupBox_connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_address.sizePolicy().hasHeightForWidth())
        self.lineEdit_address.setSizePolicy(sizePolicy)
        self.lineEdit_address.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.horizontalLayout.addWidget(self.lineEdit_address)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_port = QtWidgets.QLineEdit(self.groupBox_connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_port.sizePolicy().hasHeightForWidth())
        self.lineEdit_port.setSizePolicy(sizePolicy)
        self.lineEdit_port.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout_2.addWidget(self.lineEdit_port)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_connection)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_connectionStatus = QtWidgets.QLabel(self.groupBox_connection)
        self.label_connectionStatus.setObjectName("label_connectionStatus")
        self.horizontalLayout_4.addWidget(self.label_connectionStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.groupBox_connection)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_2.addWidget(self.groupBox_connection)
        self.gridLayout_Information = QtWidgets.QGridLayout()
        self.gridLayout_Information.setObjectName("gridLayout_Information")
        self.icon_user = QtWidgets.QLabel(self.centralwidget)
        self.icon_user.setText("")
        self.icon_user.setPixmap(QtGui.QPixmap(":/icons/userNotPresent.png"))
        self.icon_user.setScaledContents(False)
        self.icon_user.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_user.setObjectName("icon_user")
        self.gridLayout_Information.addWidget(self.icon_user, 1, 0, 1, 1)
        self.icon_battery = QtWidgets.QLabel(self.centralwidget)
        self.icon_battery.setEnabled(True)
        self.icon_battery.setText("")
        self.icon_battery.setPixmap(QtGui.QPixmap(":/icons/batteryInvalid.png"))
        self.icon_battery.setScaledContents(False)
        self.icon_battery.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_battery.setObjectName("icon_battery")
        self.gridLayout_Information.addWidget(self.icon_battery, 0, 0, 1, 1)
        self.label_user = QtWidgets.QLabel(self.centralwidget)
        self.label_user.setObjectName("label_user")
        self.gridLayout_Information.addWidget(self.label_user, 1, 1, 1, 1)
        self.label_emergency = QtWidgets.QLabel(self.centralwidget)
        self.label_emergency.setObjectName("label_emergency")
        self.gridLayout_Information.addWidget(self.label_emergency, 2, 1, 1, 1)
        self.icon_emergency = QtWidgets.QLabel(self.centralwidget)
        self.icon_emergency.setText("")
        self.icon_emergency.setPixmap(QtGui.QPixmap(":/icons/emergency-invalid.png"))
        self.icon_emergency.setScaledContents(False)
        self.icon_emergency.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_emergency.setObjectName("icon_emergency")
        self.gridLayout_Information.addWidget(self.icon_emergency, 2, 0, 1, 1)
        self.label_battery = QtWidgets.QLabel(self.centralwidget)
        self.label_battery.setObjectName("label_battery")
        self.gridLayout_Information.addWidget(self.label_battery, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_Information)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButton_Log = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Log.setObjectName("pushButton_Log")
        self.verticalLayout_2.addWidget(self.pushButton_Log)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 22))
        self.menubar.setObjectName("menubar")
        self.menu_Quitter = QtWidgets.QMenu(self.menubar)
        self.menu_Quitter.setObjectName("menu_Quitter")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Quitter = QtWidgets.QAction(MainWindow)
        self.action_Quitter.setObjectName("action_Quitter")
        self.action_OpenMessageLog = QtWidgets.QAction(MainWindow)
        self.action_OpenMessageLog.setObjectName("action_OpenMessageLog")
        self.menu_Quitter.addAction(self.action_OpenMessageLog)
        self.menu_Quitter.addSeparator()
        self.menu_Quitter.addAction(self.action_Quitter)
        self.menubar.addAction(self.menu_Quitter.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robot Monitor"))
        self.label_4.setText(_translate("MainWindow", "User Angle \"Beta\" (rad)"))
        self.label_5.setText(_translate("MainWindow", "-0.61"))
        self.progressBar_Angle_Beta.setFormat(_translate("MainWindow", "%p rad"))
        self.label_6.setText(_translate("MainWindow", "0.61"))
        self.label_Beta.setText(_translate("MainWindow", "0.0 rad"))
        self.label_7.setText(_translate("MainWindow", "Angular position (rad)"))
        self.label_10.setText(_translate("MainWindow", "Angular Speed (rad/s)"))
        self.label_8.setText(_translate("MainWindow", "-0.61"))
        self.progressBar_Angular_Position.setFormat(_translate("MainWindow", "%p rad"))
        self.label_9.setText(_translate("MainWindow", "0.61"))
        self.label_11.setText(_translate("MainWindow", "-3.14"))
        self.progressBar_Angular_Speed.setFormat(_translate("MainWindow", "%p rad/s"))
        self.label_12.setText(_translate("MainWindow", "3.14"))
        self.label_AngularPosition.setText(_translate("MainWindow", "0.0 rad"))
        self.label_AngularSpeed.setText(_translate("MainWindow", "0.0 rad/s"))
        self.label_13.setText(_translate("MainWindow", "Torque (N.m)"))
        self.label_16.setText(_translate("MainWindow", "Linear Speed (m/s)"))
        self.label_14.setText(_translate("MainWindow", "-15.00"))
        self.progressBar_Torque.setFormat(_translate("MainWindow", "%p N.m"))
        self.label_15.setText(_translate("MainWindow", "15.00"))
        self.label_17.setText(_translate("MainWindow", "0.00"))
        self.progressBar_Linear_Speed.setFormat(_translate("MainWindow", "%p m/s"))
        self.label_18.setText(_translate("MainWindow", "200.00"))
        self.label_Torque.setText(_translate("MainWindow", "0.0 N.m"))
        self.label_LinearSpeed.setText(_translate("MainWindow", "0.0 m/s"))
        self.groupBox_connection.setTitle(_translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "Address:"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.label_3.setText(_translate("MainWindow", "Status:"))
        self.label_connectionStatus.setText(_translate("MainWindow", "Not connected"))
        self.label_user.setText(_translate("MainWindow", "No information"))
        self.label_emergency.setText(_translate("MainWindow", "No information"))
        self.label_battery.setText(_translate("MainWindow", "No information"))
        self.pushButton_Log.setText(_translate("MainWindow", "Show log"))
        self.menu_Quitter.setTitle(_translate("MainWindow", "M&enu"))
        self.action_Quitter.setText(_translate("MainWindow", "&Quitter"))
        self.action_OpenMessageLog.setText(_translate("MainWindow", "O&pen message log..."))
