################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_adc.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_can.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_comp.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_crc.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dac.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dbgmcu.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dma.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_exti.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_flash.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_gpio.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_i2c.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_iwdg.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_misc.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_opamp.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_pwr.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rcc.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rtc.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_spi.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_syscfg.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_tim.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_usart.c \
/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_wwdg.c 

OBJS += \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_adc.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_can.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_comp.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_crc.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dac.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dbgmcu.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dma.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_exti.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_flash.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_gpio.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_i2c.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_iwdg.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_misc.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_opamp.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_pwr.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rcc.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rtc.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_spi.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_syscfg.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_tim.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_usart.o \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_wwdg.o 

C_DEPS += \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_adc.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_can.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_comp.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_crc.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dac.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dbgmcu.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dma.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_exti.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_flash.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_gpio.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_i2c.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_iwdg.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_misc.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_opamp.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_pwr.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rcc.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rtc.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_spi.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_syscfg.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_tim.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_usart.d \
./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_wwdg.d 


# Each subdirectory must supply rules for building sources it contributes
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_adc.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_adc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_adc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_can.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_can.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_can.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_comp.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_comp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_comp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_crc.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_crc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_crc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dac.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dac.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dac.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dbgmcu.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dbgmcu.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dbgmcu.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dma.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_exti.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_exti.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_exti.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_flash.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_flash.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_gpio.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_i2c.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_i2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_iwdg.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_iwdg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_iwdg.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_misc.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_misc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_misc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_opamp.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_opamp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_opamp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_pwr.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_pwr.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rcc.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rtc.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rtc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rtc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_spi.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_spi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_spi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_syscfg.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_syscfg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_syscfg.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_tim.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_usart.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_usart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_wwdg.o: /home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_wwdg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F30 -DUSE_STDPERIPH_DRIVER -DSTM32F303VCTx -DSTM32 -DSTM32F3 -DSTM32F3DISCOVERY -DDEBUG -c -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/CMSIS/Device/ST/STM32F30x/Include" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/STM32F30x_StdPeriph_Driver/inc" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Libraries/Utilities/STM32F3_Discovery" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil" -I"/home/dimercur/Documents/Travail/git/segway/stm32/segway/Project/Keil/Service" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_wwdg.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

